# Generated by Django 5.0.1 on 2024-01-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="email",),
    ]
